# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_mylostnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylostnotice',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mylostnotice',
            name='ligation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mylostnotice',
            name='petgender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mylostnotice',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mylostnotice',
            name='time',
            field=models.DateField(default=0),
        ),
    ]
