# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_delete_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylostnotice',
            name='ligation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mylostnotice',
            name='petgender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mylostnotice',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
