# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_mylostnotice_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
    ]
